# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: thewalters 0.2.1 ruby lib

Gem::Specification.new do |s|
  s.name = "thewalters"
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jonathan Julian"]
  s.date = "2014-01-19"
  s.description = "Easily get object metadata from The Walters API"
  s.email = "jonathan@jonathanjulian.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/thewalters-ruby.rb",
    "lib/thewalters.rb",
    "lib/thewalters/art_object.rb",
    "lib/thewalters/base.rb",
    "lib/thewalters/collection.rb",
    "lib/thewalters/exhibition.rb",
    "lib/thewalters/geography.rb",
    "lib/thewalters/location.rb",
    "test/helper.rb",
    "test/test_base.rb",
    "thewalters.gemspec"
  ]
  s.homepage = "http://github.com/WaltersArtMuseum/thewalters-ruby"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.11"
  s.summary = "A Ruby gem for communicating with The Walters API"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hashie>, [">= 1.2.0"])
      s.add_runtime_dependency(%q<faraday>, [">= 0.8.1"])
      s.add_runtime_dependency(%q<json>, [">= 1.7.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.7"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
    else
      s.add_dependency(%q<hashie>, [">= 1.2.0"])
      s.add_dependency(%q<faraday>, [">= 0.8.1"])
      s.add_dependency(%q<json>, [">= 1.7.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
      s.add_dependency(%q<mocha>, [">= 0"])
    end
  else
    s.add_dependency(%q<hashie>, [">= 1.2.0"])
    s.add_dependency(%q<faraday>, [">= 0.8.1"])
    s.add_dependency(%q<json>, [">= 1.7.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
    s.add_dependency(%q<mocha>, [">= 0"])
  end
end

