require 'json'
require 'hashie'
require 'faraday'
require 'thewalters/base'
require 'thewalters/art_object'
require 'thewalters/collection'
require 'thewalters/geography'
require 'thewalters/exhibition'
